//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Polegche
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Виды.
    /// </summary>
    // *** Start programmer edit section *** (Виды CustomAttributes)

    // *** End programmer edit section *** (Виды CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Виды : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fМестоОбитания;
        
        // *** Start programmer edit section *** (Виды CustomMembers)

        // *** End programmer edit section *** (Виды CustomMembers)

        
        /// <summary>
        /// МестоОбитания.
        /// </summary>
        // *** Start programmer edit section *** (Виды.МестоОбитания CustomAttributes)

        // *** End programmer edit section *** (Виды.МестоОбитания CustomAttributes)
        [StrLen(255)]
        public virtual string МестоОбитания
        {
            get
            {
                // *** Start programmer edit section *** (Виды.МестоОбитания Get start)

                // *** End programmer edit section *** (Виды.МестоОбитания Get start)
                string result = this.fМестоОбитания;
                // *** Start programmer edit section *** (Виды.МестоОбитания Get end)

                // *** End programmer edit section *** (Виды.МестоОбитания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Виды.МестоОбитания Set start)

                // *** End programmer edit section *** (Виды.МестоОбитания Set start)
                this.fМестоОбитания = value;
                // *** Start programmer edit section *** (Виды.МестоОбитания Set end)

                // *** End programmer edit section *** (Виды.МестоОбитания Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Виды.Наименование CustomAttributes)

        // *** End programmer edit section *** (Виды.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Виды.Наименование Get start)

                // *** End programmer edit section *** (Виды.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Виды.Наименование Get end)

                // *** End programmer edit section *** (Виды.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Виды.Наименование Set start)

                // *** End programmer edit section *** (Виды.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Виды.Наименование Set end)

                // *** End programmer edit section *** (Виды.Наименование Set end)
            }
        }
    }
}
