//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Polegche
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Животные.
    /// </summary>
    // *** Start programmer edit section *** (Животные CustomAttributes)

    // *** End programmer edit section *** (Животные CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Животные : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЖивотного;
        
        private string fКличка;
        
        private IIS.Polegche.Пол fПол;
        
        private IIS.Polegche.Виды fВиды;
        
        // *** Start programmer edit section *** (Животные CustomMembers)

        // *** End programmer edit section *** (Животные CustomMembers)

        
        /// <summary>
        /// Кличка.
        /// </summary>
        // *** Start programmer edit section *** (Животные.Кличка CustomAttributes)

        // *** End programmer edit section *** (Животные.Кличка CustomAttributes)
        [StrLen(255)]
        public virtual string Кличка
        {
            get
            {
                // *** Start programmer edit section *** (Животные.Кличка Get start)

                // *** End programmer edit section *** (Животные.Кличка Get start)
                string result = this.fКличка;
                // *** Start programmer edit section *** (Животные.Кличка Get end)

                // *** End programmer edit section *** (Животные.Кличка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.Кличка Set start)

                // *** End programmer edit section *** (Животные.Кличка Set start)
                this.fКличка = value;
                // *** Start programmer edit section *** (Животные.Кличка Set end)

                // *** End programmer edit section *** (Животные.Кличка Set end)
            }
        }
        
        /// <summary>
        /// КодЖивотного.
        /// </summary>
        // *** Start programmer edit section *** (Животные.КодЖивотного CustomAttributes)

        // *** End programmer edit section *** (Животные.КодЖивотного CustomAttributes)
        public virtual int КодЖивотного
        {
            get
            {
                // *** Start programmer edit section *** (Животные.КодЖивотного Get start)

                // *** End programmer edit section *** (Животные.КодЖивотного Get start)
                int result = this.fКодЖивотного;
                // *** Start programmer edit section *** (Животные.КодЖивотного Get end)

                // *** End programmer edit section *** (Животные.КодЖивотного Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.КодЖивотного Set start)

                // *** End programmer edit section *** (Животные.КодЖивотного Set start)
                this.fКодЖивотного = value;
                // *** Start programmer edit section *** (Животные.КодЖивотного Set end)

                // *** End programmer edit section *** (Животные.КодЖивотного Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (Животные.Пол CustomAttributes)

        // *** End programmer edit section *** (Животные.Пол CustomAttributes)
        public virtual IIS.Polegche.Пол Пол
        {
            get
            {
                // *** Start programmer edit section *** (Животные.Пол Get start)

                // *** End programmer edit section *** (Животные.Пол Get start)
                IIS.Polegche.Пол result = this.fПол;
                // *** Start programmer edit section *** (Животные.Пол Get end)

                // *** End programmer edit section *** (Животные.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.Пол Set start)

                // *** End programmer edit section *** (Животные.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (Животные.Пол Set end)

                // *** End programmer edit section *** (Животные.Пол Set end)
            }
        }
        
        /// <summary>
        /// Животные.
        /// </summary>
        // *** Start programmer edit section *** (Животные.Виды CustomAttributes)

        // *** End programmer edit section *** (Животные.Виды CustomAttributes)
        [PropertyStorage(new string[] {
                "Виды"})]
        [NotNull()]
        public virtual IIS.Polegche.Виды Виды
        {
            get
            {
                // *** Start programmer edit section *** (Животные.Виды Get start)

                // *** End programmer edit section *** (Животные.Виды Get start)
                IIS.Polegche.Виды result = this.fВиды;
                // *** Start programmer edit section *** (Животные.Виды Get end)

                // *** End programmer edit section *** (Животные.Виды Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.Виды Set start)

                // *** End programmer edit section *** (Животные.Виды Set start)
                this.fВиды = value;
                // *** Start programmer edit section *** (Животные.Виды Set end)

                // *** End programmer edit section *** (Животные.Виды Set end)
            }
        }
    }
}
