//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Polegche
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Уборка.
    /// </summary>
    // *** Start programmer edit section *** (Уборка CustomAttributes)

    // *** End programmer edit section *** (Уборка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Уборка : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДеньУборки;
        
        private string fВремяУборки;
        
        private IIS.Polegche.Должность fДолжность;
        
        private IIS.Polegche.Вольер fВольер;
        
        // *** Start programmer edit section *** (Уборка CustomMembers)

        // *** End programmer edit section *** (Уборка CustomMembers)

        
        /// <summary>
        /// ВремяУборки.
        /// </summary>
        // *** Start programmer edit section *** (Уборка.ВремяУборки CustomAttributes)

        // *** End programmer edit section *** (Уборка.ВремяУборки CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяУборки
        {
            get
            {
                // *** Start programmer edit section *** (Уборка.ВремяУборки Get start)

                // *** End programmer edit section *** (Уборка.ВремяУборки Get start)
                string result = this.fВремяУборки;
                // *** Start programmer edit section *** (Уборка.ВремяУборки Get end)

                // *** End programmer edit section *** (Уборка.ВремяУборки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Уборка.ВремяУборки Set start)

                // *** End programmer edit section *** (Уборка.ВремяУборки Set start)
                this.fВремяУборки = value;
                // *** Start programmer edit section *** (Уборка.ВремяУборки Set end)

                // *** End programmer edit section *** (Уборка.ВремяУборки Set end)
            }
        }
        
        /// <summary>
        /// ДеньУборки.
        /// </summary>
        // *** Start programmer edit section *** (Уборка.ДеньУборки CustomAttributes)

        // *** End programmer edit section *** (Уборка.ДеньУборки CustomAttributes)
        public virtual System.DateTime ДеньУборки
        {
            get
            {
                // *** Start programmer edit section *** (Уборка.ДеньУборки Get start)

                // *** End programmer edit section *** (Уборка.ДеньУборки Get start)
                System.DateTime result = this.fДеньУборки;
                // *** Start programmer edit section *** (Уборка.ДеньУборки Get end)

                // *** End programmer edit section *** (Уборка.ДеньУборки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Уборка.ДеньУборки Set start)

                // *** End programmer edit section *** (Уборка.ДеньУборки Set start)
                this.fДеньУборки = value;
                // *** Start programmer edit section *** (Уборка.ДеньУборки Set end)

                // *** End programmer edit section *** (Уборка.ДеньУборки Set end)
            }
        }
        
        /// <summary>
        /// Уборка.
        /// </summary>
        // *** Start programmer edit section *** (Уборка.Вольер CustomAttributes)

        // *** End programmer edit section *** (Уборка.Вольер CustomAttributes)
        [PropertyStorage(new string[] {
                "Вольер"})]
        [NotNull()]
        public virtual IIS.Polegche.Вольер Вольер
        {
            get
            {
                // *** Start programmer edit section *** (Уборка.Вольер Get start)

                // *** End programmer edit section *** (Уборка.Вольер Get start)
                IIS.Polegche.Вольер result = this.fВольер;
                // *** Start programmer edit section *** (Уборка.Вольер Get end)

                // *** End programmer edit section *** (Уборка.Вольер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Уборка.Вольер Set start)

                // *** End programmer edit section *** (Уборка.Вольер Set start)
                this.fВольер = value;
                // *** Start programmer edit section *** (Уборка.Вольер Set end)

                // *** End programmer edit section *** (Уборка.Вольер Set end)
            }
        }
        
        /// <summary>
        /// Уборка.
        /// </summary>
        // *** Start programmer edit section *** (Уборка.Должность CustomAttributes)

        // *** End programmer edit section *** (Уборка.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Polegche.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Уборка.Должность Get start)

                // *** End programmer edit section *** (Уборка.Должность Get start)
                IIS.Polegche.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Уборка.Должность Get end)

                // *** End programmer edit section *** (Уборка.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Уборка.Должность Set start)

                // *** End programmer edit section *** (Уборка.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Уборка.Должность Set end)

                // *** End programmer edit section *** (Уборка.Должность Set end)
            }
        }
    }
}
